version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    command: npm run dev
